# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  doctor:
    build:
      context: .
      args:
        ALPINE_VERSION: "3.20"
    environment:
      S3_REGION:
      S3_ACCESS_KEY_ID:
      S3_SECRET_ACCESS_KEY:
      S3_BUCKET:
      S3_PREFIX:
      S3_ENDPOINT:
      CALLBACK_URL:
      CRON_SCHEDULE: "* * * * *"
      PASSPHRASE: passphrase
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp:/backups
